services:
  - type: web
    name: ubunifu-backend
    env: node
    buildCommand: pnpm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
